# Misc variables that will only stand in for text

insults = [
    "Looks like gravity just added you to its frag list!",
    "Were you trying a pacifist run, or...?",
    "Maybe we should start calling you 'Captain Respawn'.",
    "Oops! Did your controller disconnect again? 😉",
    "You're not just playing dead for the dramatic effect, right?",
    "Achievement unlocked: Professional Cliff Diver.",
    "Do you have a loyalty card for the afterlife? Because you might get a free coffee soon!",
    "Even Schrödinger's cat knew when to stay in the box.",
    "Careful, or you'll turn 'dying in-game' into an art form.",
    "You've got the 'dying heroically' part down; now let's work on the 'not dying' bit.",
    "Reload last checkpoint? Just kidding, we know you don't have one. 😆",
    "Trying to increase your ghost followers on Hauntstagram?",
    "There's aggressive play, and then there's whatever you just did.",
    "Don't worry, it's only game over until you hit 'retry'.",
    "Your character called; they want their extra lives back.",
    "Quick question: You know this isn't a 'who dies the most' competition, right?",
    "Your demise was... unexpected. Almost like your strategy.",
    "Was that a tactical reset or did you just trip over your own feet again?",
    "Some say practice makes perfect. How are you feeling about that phrase right about now?",
    "At this point, the enemies are just completing their daily kill quota with you.",
    "If you were trying to give the floor a hug, mission accomplished!",
    "Are your life points on a discount? Because you're giving them away so freely!",
    "Your respawn button must be getting a great workout today!",
    "Who knew playing dead could be a full-time job?",
    "All those hours playing and you've decided to become a philanthropist for the death count charity.",
    "Ever considered that 'survivor' might be a more fitting role than 'target practice'?",
    "Hope you're not planning to start a career as a stunt double... for a ragdoll.",
    "Was it a strategic fall or are you auditioning for a role in 'The Walking Dead'? Because, bravo!",
    "Heads up! Or not... Seems like gravity's stronger on your character.",
    "Your 'dodge' key must be broken. No one can have reflexes that slow, right?"
    "You're like a reverse phoenix; instead of rising from the ashes, you just... well, you know.",
    "Hide and seek champion... as long as the goal is to be found immediately.",
    "Did they remap the 'jump' button, or are you just experimenting with gravity?",
    "Legend has it that every time you die in-game, a developer gets their wings.",
    "Seriously considering a petition to rename the 'floor' to 'your second home'.",
    "You're not lagging, you're just taking a more 'creative' approach to staying alive, right?",
    "The art of respawning: some have painting, you have dying and coming back. Over and over.",
    "Let me guess, you were trying to test if you had nine lives? Spoiler: you don't.",
    "Your nemesis isn't the boss. It's not the traps. It's... literally just staying alive.",
    "Oh look, your character is taking a nap again. On the spikes. How quaint.",
    "Do you ever wonder if your character feels deja vu every time they’re brought back?",
    "Someone should really teach your avatar about self-preservation one of these days.",
    "You must be going for a high score... in how many times one can bite the dust.",
    "Wanted: One gamer. Skills required: basic survival instincts. Apparently, there's an opening."
]